"""Initial migration"""


from alembic import  op 
import sqlalchemy as  sa 

# revision identifier, used by Alembic,
revision = "5ec574d4788a"
down_revision = None
branch_labels = None
depends_on = None 

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table("book", schema=None) as batch_op: 
         batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
         batch_op.create_foreign_key(
             "fk_book_user_id", "user",["user_id"], ["id"]
             #Added a name to the foreign Key
         )
         
        ### end alembic commands ##
        
    def downgrade():
         ### commands auto generated by Alembic - please addjust! ###
         with op.batch_alter_table("books" , schema=None) as batch_op:
             batch_op.drop_constraint(
                 "fk_book_user_id", type_="Foreignkey"
                 # Use the constraint name
             )
             batch_op.drop_column("user_id")